spring.application.name=Loan-Management-System

spring.datasource.url=jdbc:postgresql://localhost:5432/loan_db
spring.datasource.username=postgres
spring.datasource.password=Temp@123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Auth Settings
app.jwt.expiration-ms=604800000
app.jwt.secret=FaSwA9tkVQdmhdFLRFh7Bh1i/Tfrg51fJhtc1ioWQlIsONWBE3z7BXxt5FwIEf5OvlLhRqwvQxWNQNzgK/fQpQ==

# Email Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jotangiatanmay840@gmail.com
spring.mail.password=ecnu lxll eovx vbiw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=jotangiatanmay840@gmail.com

# Cloudinary Configuration
cloudinary.cloud_name=dntjs5mdo
cloudinary.api_key=754729656199146
cloudinary.api_secret=RflGhgpUwPsV7PVJIbcZdKcgh5I





